// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from debug_flag.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCDebugFlag)
{
    NCDebugFlagNone,
    NCDebugFlagInfos,
    NCDebugFlagStats,
    NCDebugFlagLabels,
    NCDebugFlagDrawAllLabels,
    NCDebugFlagSelectionBuffer,
};
