// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from position_listener.djinni

#import "NCExport.h"
#import "NCPosition.h"
#import <Foundation/Foundation.h>


DEFAULT_EXPORT_ATTRIBUTE
@protocol NCPositionListener <NSObject>

- (void)onPositionUpdated:(nonnull NCPosition *)position;

- (void)onPositionError:(nullable NSError *)error;

@end
