// navigine.h
// navigine

#import <Foundation/Foundation.h>

//! Project version number for navigine.
FOUNDATION_EXPORT double navigineVersionNumber;

//! Project version string for navigine.
FOUNDATION_EXPORT const unsigned char navigineVersionString[];

#import "NCRectangle.h"
#import "NCBitmapRegionDecoder.h"
#import "NCResourceUploadListener.h"
#import "NCResourceListener.h"
#import "NCResourceManager.h"
#import "NCRouteListener.h"
#import "NCRouteManager.h"
#import "NCAsyncRouteListener.h"
#import "NCRouteSession.h"
#import "NCAsyncRouteManager.h"
#import "NCZoneListener.h"
#import "NCZoneManager.h"
#import "NCNotification.h"
#import "NCNotificationListener.h"
#import "NCNotificationManager.h"
#import "NCNavigineSdk.h"
#import "NCPosition.h"
#import "NCPositionListener.h"
#import "NCNavigationManager.h"
#import "NCMultiLineMapObject.h"
#import "NCMeasurementManager.h"
#import "NCMeasurementListener.h"
#import "NCSensorType.h"
#import "NCSignalType.h"
#import "NCVector3d.h"
#import "NCSensorMeasurement.h"
#import "NCSignalMeasurement.h"
#import "NCCircleMapObject.h"
#import "NCPickListener.h"
#import "NCMapObjectPickResult.h"
#import "NCLocationPolygon.h"
#import "NCLocationManager.h"
#import "NCLocationListener.h"
#import "NCLocationListManager.h"
#import "NCLocationListListener.h"
#import "NCLocationViewListener.h"
#import "NCLocationInfo.h"
#import "NCLocationEditManager.h"
#import "NCLocationEditListener.h"
#import "NCRouteEventType.h"
#import "NCRouteEvent.h"
#import "NCRoutePath.h"
#import "NCWifi.h"
#import "NCZone.h"
#import "NCVenue.h"
#import "NCReferenceEntryType.h"
#import "NCReferenceEntry.h"
#import "NCReferencePoint.h"
#import "NCSublocation.h"
#import "NCLocation.h"
#import "NCPolyline.h"
#import "NCLocationPolyline.h"
#import "NCPolylineMapObject.h"
#import "NCLine.h"
#import "NCGraph.h"
#import "NCMapObjectType.h"
#import "NCMapObject.h"
#import "NCLocationPoint.h"
#import "NCIconMapObject.h"
#import "NCImageType.h"
#import "NCImage.h"
#import "NCGlobalPoint.h"
#import "NCPolygon.h"
#import "NCSegment.h"
#import "NCGeometryUtils.h"
#import "NCGraphEdge.h"
#import "NCGraphVertex.h"
#import "NCElevationGraph.h"
#import "NCEddystone.h"
#import "NCCategory.h"
#import "NCPoint.h"
#import "NCBeacon.h"
#import "NCAnimationType.h"
#import "NCLocationView.h"
#import "NCGestureRecognizerDelegate.h"
#import "NCExport.h"
