// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from camera.djinni

#import "NCExport.h"
#import "NCPoint.h"
#import <Foundation/Foundation.h>

NAVIGINE_EXPORT
@interface NCCamera : NSObject
- (nonnull instancetype)initWithPoint:(nonnull NCPoint *)point
                                 zoom:(float)zoom;
+ (nonnull instancetype)cameraWithPoint:(nonnull NCPoint *)point
                                   zoom:(float)zoom;

@property (nonatomic, readonly, nonnull) NCPoint * point;

@property (nonatomic, readonly) float zoom;

@end
