// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from category.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>

DEFAULT_EXPORT_ATTRIBUTE
@interface NCCategory : NSObject
- (nonnull instancetype)initWithId:(int32_t)id
                              name:(nonnull NSString *)name
                          imageUrl:(nullable NSString *)imageUrl;
+ (nonnull instancetype)categoryWithId:(int32_t)id
                                  name:(nonnull NSString *)name
                              imageUrl:(nullable NSString *)imageUrl;

@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nullable) NSString * imageUrl;

@end
