// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from image.djinni

#import "NCExport.h"
#import "NCImageType.h"
#import <Foundation/Foundation.h>


NAVIGINE_EXPORT
@interface NCImage : NSObject

@property (nonatomic, nonnull, readonly) NSData * data;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) NCImageType type;

@end
