// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from image.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCImageType)
{
    NCImageTypePNG,
    NCImageTypeSVG,
    NCImageTypeJPG,
};
