// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from location_listener.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>
@class NCLocation;


NAVIGINE_EXPORT
@protocol NCLocationListener <NSObject>

- (void)onLocationLoaded:(nullable NCLocation *)location;

- (void)onDownloadProgress:(int32_t)locationId
                  received:(int32_t)received
                     total:(int32_t)total;

- (void)onLocationFailed:(int32_t)locationId
                   error:(nullable NSError *)error;

- (void)onLocationCancelled:(int32_t)locationId;

@end
