// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from location_view_listener.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>


NAVIGINE_EXPORT
@protocol NCLocationViewListener <NSObject>

- (void)onLocationViewComplete;

- (void)onLocationViewWillChangeAnimated:(BOOL)animated;

- (void)onLocationViewIsChanging;

- (void)onLocationViewDidChangeAnimated:(BOOL)animated;

@end
