// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from location_list_listener.djinni

#import "NCExport.h"
#import "NCLocationInfo.h"
#import <Foundation/Foundation.h>


DEFAULT_EXPORT_ATTRIBUTE
@protocol NCLocationListListener <NSObject>

- (void)onLocationListLoaded:(nonnull NSDictionary<NSNumber *, NCLocationInfo *> *)locationInfos;

- (void)onLocationListFailed:(nullable NSError *)error;

@end
