// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multi_line_map_object.djinni

#import "NCExport.h"
#import "NCPoint.h"
#import <Foundation/Foundation.h>


NAVIGINE_EXPORT
@interface NCMultiLineMapObject : NSObject

- (void)setLines:(nonnull NSArray<NSArray<NCPoint *> *> *)lines;

- (void)setWidth:(float)width;

- (float)getWidth;

- (void)setData:(nonnull NSData *)data;

- (nonnull NSData *)getData;

- (void)setEnabled:(BOOL)visibility;

- (void)setColor:(float)red
           green:(float)green
            blue:(float)blue
           alpha:(float)alpha;

@end
