// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from point.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>

NAVIGINE_EXPORT
@interface NCPoint : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y;
+ (nonnull instancetype)pointWithX:(float)x
                                 y:(float)y;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@end
