// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from position_listener.djinni

#import "NCExport.h"
#import "NCPosition.h"
#import <Foundation/Foundation.h>


NAVIGINE_EXPORT
@protocol NCPositionListener <NSObject>

- (void)onPositionUpdated:(nonnull NCPosition *)position;

- (void)onPositionError:(nullable NSError *)error;

@end
