// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from reference_point.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCReferenceEntryType)
{
    NCReferenceEntryTypeBEACON,
    NCReferenceEntryTypeWIFI,
    NCReferenceEntryTypeBLE,
    NCReferenceEntryTypeEDDYSTONE,
    NCReferenceEntryTypeMAGNET,
};
