// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from reference_point.djinni

#import "NCExport.h"
#import "NCReferenceEntryType.h"
#import <Foundation/Foundation.h>


NAVIGINE_EXPORT
@interface NCReferenceEntry : NSObject

@property (nonatomic, readonly) NCReferenceEntryType type;

@property (nonatomic, nonnull, readonly) NSString * bssid;

@property (nonatomic, nonnull, readonly) NSString * value;

@end
