// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from camera_listener.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCCameraUpdateReason)
{
    NCCameraUpdateReasonGestures,
    NCCameraUpdateReasonApplication,
};
