// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from camera_listener.djinni

#import "NCCameraUpdateReason.h"
#import "NCExport.h"
#import <Foundation/Foundation.h>


DEFAULT_EXPORT_ATTRIBUTE
@protocol NCCameraListener <NSObject>

- (void)onCameraPositionChanged:(NCCameraUpdateReason)reason
                       finished:(BOOL)finished;

@end
