// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from input_listener.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


DEFAULT_EXPORT_ATTRIBUTE
@protocol NCInputListener <NSObject>

- (void)onViewTap:(CGPoint)screenPoint;

- (void)onViewDoubleTap:(CGPoint)screenPoint;

- (void)onViewLongTap:(CGPoint)screenPoint;

@end
