// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from location_list_manager.djinni

#import "NCExport.h"
#import "NCLocationInfo.h"
#import <Foundation/Foundation.h>
@protocol NCLocationListListener;


DEFAULT_EXPORT_ATTRIBUTE
@interface NCLocationListManager : NSObject

- (void)addLocationListListener:(nullable id<NCLocationListListener>)listener;

- (void)removeLocationListListener:(nullable id<NCLocationListListener>)listener;

- (void)updateLocationList;

- (nonnull NSDictionary<NSNumber *, NCLocationInfo *> *)getLocationList;

@end
