// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from route_event.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCRouteEventType)
{
    NCRouteEventTypeTURNLEFT,
    NCRouteEventTypeTURNRIGHT,
    NCRouteEventTypeTRANSITION,
};
