// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from transmitter_status.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCTransmitterStatus)
{
    NCTransmitterStatusNone,
    NCTransmitterStatusNew,
    NCTransmitterStatusDeleted,
    NCTransmitterStatusModified,
};
