// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from location_window.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>



typedef void (^NCCameraCallback)(BOOL completed);

