// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from flat_icon_map_object.djinni

#import "NCAnimationType.h"
#import "NCExport.h"
#import "NCIconMapObject.h"
#import <Foundation/Foundation.h>


DEFAULT_EXPORT_ATTRIBUTE
@interface NCFlatIconMapObject : NCIconMapObject

- (BOOL)setAngle:(double)angle;

- (BOOL)setAngleAnimated:(double)angle
                duration:(float)duration
                    type:(NCAnimationType)type;

@end
