// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from global_point.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>

DEFAULT_EXPORT_ATTRIBUTE
@interface NCGlobalPoint : NSObject
- (nonnull instancetype)initWithLatitude:(double)latitude
                               longitude:(double)longitude;
+ (nonnull instancetype)globalPointWithLatitude:(double)latitude
                                      longitude:(double)longitude;

@property (nonatomic, readonly) double latitude;

@property (nonatomic, readonly) double longitude;

@end
