// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graph_edge.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>


DEFAULT_EXPORT_ATTRIBUTE
@interface NCGraphEdge : NSObject

@property (nonatomic, readonly) float weight;

@property (nonatomic, readonly) int32_t dst;

@property (nonatomic, readonly) int32_t src;

@property (nonatomic, readonly) int32_t weightCoef;

@end
