// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from measurement.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCSignalType)
{
    NCSignalTypeWIFI,
    NCSignalTypeBEACON,
    NCSignalTypeBLUETOOTH,
    NCSignalTypeEDDYSTONE,
    NCSignalTypeWIFIRTT,
};
