// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from zone_listener.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>
@class NCZone;


DEFAULT_EXPORT_ATTRIBUTE
@protocol NCZoneListener <NSObject>

- (void)onEnterZone:(nullable NCZone *)zone;

- (void)onLeaveZone:(nullable NCZone *)zone;

@end
