// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graph.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>
@class NCGraphEdge;
@class NCGraphVertex;


NAVIGINE_EXPORT
@interface NCGraph : NSObject

@property (nonatomic, nonnull, readonly) NSArray<NCGraphVertex *> * vertexes;

@property (nonatomic, nonnull, readonly) NSArray<NCGraphEdge *> * edges;

@end
