// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from location_listener.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>
@class NCLocation;


DEFAULT_EXPORT_ATTRIBUTE
@protocol NCLocationListener <NSObject>

- (void)onLocationLoaded:(nullable NCLocation *)location;

- (void)onLocationFailed:(int32_t)locationId
                   error:(nullable NSError *)error;

- (void)onLocationUploaded:(int32_t)locationId;

@end
