// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from location_edit_listener.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>


NAVIGINE_EXPORT
@protocol NCLocationEditListener <NSObject>

- (void)onLocationEditError:(nullable NSError *)error;

@end
