// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from measurement_listener.djinni

#import "NCExport.h"
#import "NCSensorMeasurement.h"
#import "NCSensorType.h"
#import "NCSignalMeasurement.h"
#import <Foundation/Foundation.h>


NAVIGINE_EXPORT
@protocol NCMeasurementListener <NSObject>

- (void)onSensorMeasurementDetected:(nonnull NSDictionary<NSNumber *, NCSensorMeasurement *> *)sensors;

- (void)onSignalMeasurementDetected:(nonnull NSDictionary<NSString *, NCSignalMeasurement *> *)signals;

@end
