// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from notification_listener.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>
@class NCNotification;


DEFAULT_EXPORT_ATTRIBUTE
@protocol NCNotificationListener <NSObject>

- (void)onNotificationLoaded:(nullable NCNotification *)notification;

- (void)onNotificationFailed:(nullable NSError *)error;

@end
