// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from rectangle.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>

NAVIGINE_EXPORT
@interface NCRectangle : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                            width:(float)width
                           height:(float)height;
+ (nonnull instancetype)rectangleWithX:(float)x
                                     y:(float)y
                                 width:(float)width
                                height:(float)height;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@property (nonatomic, readonly) float width;

@property (nonatomic, readonly) float height;

@end
