// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from route_session.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>
@protocol NCAsyncRouteListener;


DEFAULT_EXPORT_ATTRIBUTE
@interface NCRouteSession : NSObject

- (void)addRouteListener:(nullable id<NCAsyncRouteListener>)listener;

- (void)removeRouteListener:(nullable id<NCAsyncRouteListener>)listener;

@end
