// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from animation_type.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NCAnimationType)
{
    NCAnimationTypeNone,
    NCAnimationTypeLinear,
    NCAnimationTypeCubic,
    NCAnimationTypeQuint,
    NCAnimationTypeSine,
};
