// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from beacon_proximity_estimator.djinni

#import "NCExport.h"
#import <Foundation/Foundation.h>

DEFAULT_EXPORT_ATTRIBUTE
@interface NCBeaconProximityEntry : NSObject
- (nonnull instancetype)initWithTx:(nonnull NSString *)tx
                              rssi:(float)rssi
                         frequency:(float)frequency
                           quality:(float)quality
                          distance:(nullable NSNumber *)distance;
+ (nonnull instancetype)beaconProximityEntryWithTx:(nonnull NSString *)tx
                                              rssi:(float)rssi
                                         frequency:(float)frequency
                                           quality:(float)quality
                                          distance:(nullable NSNumber *)distance;

@property (nonatomic, readonly, nonnull) NSString * tx;

@property (nonatomic, readonly) float rssi;

@property (nonatomic, readonly) float frequency;

@property (nonatomic, readonly) float quality;

@property (nonatomic, readonly, nullable) NSNumber * distance;

@end
